@startuml Contrato Menor 
|Servicio|
start


|Contratación|
  :abrir expediente bookmark:https://gestiona-08.espublico.com;
  :abrir tarjeta bookmark:https://wekan.cristobalmoyalopez.es/b/44DcK8YTRA9gnX73A/contratos-menores;
repeat   
|Servicio|  
  :Ficha de contratación ;
  :Informe de necesidad;
|Técnico|
:Redactar prescripciones técnicas/proyecto obras;
:Firma prescripciones técnicas;
|Contratación|
  :Repasar y comprobar que es correcto;
  backward:Avisar al servicio para que rectifique el error;
repeat while (¿Hay que rectificar la documentación?) is (Si) 
   
|Contratación|
:Enviar a la firma;
If (¿es de urbanismo) Then (Si)
|Concejal del servicio|
:firma la ficha y el informe de necesidad;
else (No)
|Técnico|
:Firma informe de necesidad;
|Concejal del servicio|
:Firma ficha;
endif
|Contratación|
:Solicitar RC;
|Intervención|
:Emite RC;
if(¿Existe crédito) then (Si)
|Contratación|
:Redactar la providencia de inicio:
:Enviar a la firma del concejal del servicio;
else (No)
|Contratación|
:Avisar al concejal;
endif
|Contratación|
:Redactar providencia inicio;
:Enviar firma (concejal del servicio y alcalde);
|Concejal del servicio|
:Firma;
|Alcalde|
:Firma;
|Contratación|
:preparar informe Secretario;
:Enviar a la firma Secretario;
|Secretario|
:firma;
|Contratación|
:Preparar invitaciones;
:adjuntar Memoria técnica, modelo de declaración responsable y modelo de oferta econonómica;
:Enviar al registro de salida;
:Enviar a la firma (secretario valida y concejal de contratación firma);
|Secretario|
:Valida;
|Concejal de contratación|
:firma;
|Contratación|
#e0e0e0:⏳ Esperar plazo de ofertas;
:Abrir sobres;
:Comprobar que son correctos;
:incluir ofertas en expediente;
:Preparar propuesta de adjudicación sin fiscalización;
:Enviar a la firma (Secretario y Concejal de contratación);
|Secretario|
:firma;
|Concejal de contratación|
:Firma;
|Junta de Gobierno|
:Acuerda la adjudicación;
|Contratación|
:Notificación;


stop
@enduml